# Generated by Django 5.0.7 on 2024-07-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importjob',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='importjob',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='importjob',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importjob',
            name='schedule_days',
            field=models.CharField(blank=True, max_length=21),
        ),
        migrations.AddField(
            model_name='importjob',
            name='schedule_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
